server:
  port: 8083
spring:
  redis:
    host: 192.168.198.129
    port: 6379
    timeout: 20
  #   password:
  #    pool:
  #      max-active: 8
  #    # 连接池最大阻塞等待时间（使用负值表示没有限制）
  #      max-wait: -1
  #    # 连接池中的最大空闲连接
  #      max-idle: 8
  #    # 连接池中的最小空闲连接
  #      min-idle: 0
  application:
    name: stock-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.198.129:28848

